### ISSUE TITLE
The weight file cannot be downloaded

### ISSUE THREAD

**Issue by XLionXL** [DaLi-Jack/SSR-code#1]
Thank you very much for your work, but the pre training weight link I found on Github did not redirect properly. I cannot find the download path. Can you help me solve this problem?

**Comment by DaLi-Jack** [comment]
Hi! I'm glad to know that our work is useful to you. 
Due to the large amount of processed data, we are organizing and searching for suitable methods to upload it. The ckpts will also be uploaded together, and we will complete it within one or two days. 
Once completed, I will notify you immediately!

**Comment by DaLi-Jack** [comment]
We have uploaded data and ckpts, please check the README again!

**Comment by XLionXL** [comment]
I'm sorry I just saw your email, thank you very much for your work!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junfeng ***@***.***&gt;; 
发送时间: 2023年11月4日(星期六) 晚上6:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DaLi-Jack/SSR-code] The weight file cannot be downloaded (Issue #1)





 
We have uploaded data and ckpts, please check the README again!

**Comment by Liuzhengli** [comment]
The dataset is too large to download. How can I handle this?
