### ISSUE TITLE
Error when Testing on SUNRGB-D dataset 

### ISSUE THREAD

**Issue by Cindy0725** [DaLi-Jack/SSR-code#3]
Hi, I am trying to run "python inference_sunrgbd.py --config configs/train_sunrgbd.yaml", but got the following error: 

![1699330439925](https://github.com/DaLi-Jack/SSR-code/assets/38576019/117e6d33-bfd3-4f6e-950c-df48eba2b6c5)

It seems that the paths "/home/newdisk/merge-data" and "/home/newdisk/BigData/sunrgbd_det_results/visualization" in the train_sunrgbd.yaml file are missing. Could you please help with the problem? 

Thank you very much! Looking forward to your kind reply.

**Comment by DaLi-Jack** [comment]
Hi! Sorry, I forgot to change the SUNRGBD config and upload the detection results for SUNRGBD data, thank you very much for your reminder! I have already updated the code and SUNRGBD data, please update your local files.

**Comment by Cindy0725** [comment]
> Hi! Sorry, I forgot to change the SUNRGBD config and upload the detection results for SUNRGBD data, thank you very much for your reminder! I have already updated the code and SUNRGBD data, please update your local files.

Hi, thank you very much for your quick reply. I checked the code and files, it worked now! 
btw I see you train and test on Pix3D and FRONT3D dataset in the paper. I am wondering whether you have trained the model on SUNRGB-D dataset. If so, could you please also provide the data-preprocessing procedure and the SUNRGB-D training code?

**Comment by DaLi-Jack** [comment]
We didn't train on SUNRGBD, because SUNRGBD doesn't provide GT mesh, only point cloud is provided. And the point cloud is not accurate enough for individual objects so it's a little difficult for us to generate GT SDF.
A more important reason is that we want to show the generalization ability of our model on SUNRGBD, so we directly use the model trained on FRONT3D to test on SUNRGBD.
You can refer to [Total3D](https://github.com/GAP-LAB-CUHK-SZ/Total3DUnderstanding#data-preparation) to process the SUNRGBD dataset.

**Comment by Cindy0725** [comment]
Okay! Sorry that I forgot SUNRGBD dataset doesn't provide GT mesh. Have a nice day!

**Comment by csyhping** [comment]
Hi @DaLi-Jack , is it able to do novel view synthesis or fusion on SUNRGBD? I tried to replace the command [NVS](https://github.com/DaLi-Jack/SSR-code?tab=readme-ov-file#novel-view-synthesis) by changing the front3d,yaml to sunrgbd.yaml but got error. Do you have any idea on this? Thanks!

**Comment by DaLi-Jack** [comment]
> Hi @DaLi-Jack , is it able to do novel view synthesis or fusion on SUNRGBD? I tried to replace the command [NVS](https://github.com/DaLi-Jack/SSR-code?tab=readme-ov-file#novel-view-synthesis) by changing the front3d,yaml to sunrgbd.yaml but got error. Do you have any idea on this? Thanks!

Yes, of course. Directly modifying the configuration will cause errors because SUNRGBD is a real-world dataset and lacks many object parameters available in FRONT3D. As a result, the parameters in [SUNRGBD's dataloader](https://github.com/DaLi-Jack/SSR-code/blob/d40bd0226ae6f9169a37efd8a84a7a0a50467997/ssr/dataloader/sunrgbd_dataloader.py#L249) are not the same as those in [FRONT3D's dataloader](https://github.com/DaLi-Jack/SSR-code/blob/d40bd0226ae6f9169a37efd8a84a7a0a50467997/ssr/dataloader/front3d_dataloader.py#L327). To address this, I wrote a [new script](https://drive.google.com/file/d/12a48byKoASQWVeruvBU1ORy8c-pcH_jw/view?usp=sharing) that hard-codes the object parameters missing from SUNRGBD. However, performance may decrease due to the hard-coded nature of the parameters. You can run the script using the command `python inference_rot_angle_sunrgbd.py --config configs/train_sunrgbd.yaml`, and be sure to set `show_rendering = True` in the `train_sunrgbd.yaml`.

**Comment by csyhping** [comment]
@DaLi-Jack Thanks for your prompt reply! It works well. When I try to go deeper into SUNRGBD's dataloader, it seems the SUNRGBD's data (the .pkl file provided in your [data link](https://drive.google.com/drive/folders/0B03EA5z0iyntfjlabzBYUzBrWXljdW9lLWZ5STB4VnZya2ROX1EtbFhPcjJEZU1aZXg5VVE?resourcekey=0-q4NP4IjcLYK_Js9Xc4ycwQ)) is preprocessed and has many dict_keys, and it is a little confusing about the keys' meaning (ie., `ori_cls`, `size_cls`, `center_cls`) so I cannot reproduce the preprocessing procedure (it seems the [JSON file](https://github.com/DaLi-Jack/SSR-code/blob/main/dataset/SUNRGBD/scene_1490.json) is from a 2D detector, but I don't know how to get the preprocessed [PKL](https://drive.google.com/drive/folders/0B03EA5z0iyntfjlabzBYUzBrWXljdW9lLWZ5STB4VnZya2ROX1EtbFhPcjJEZU1aZXg5VVE?resourcekey=0-q4NP4IjcLYK_Js9Xc4ycwQ) file from an input image). Could you please kindly provide the preprocessing script for SUNRGBD data? Many thanks!

**Comment by thousanddrowned** [comment]
So is there a way to preprocess data now?
