### ISSUE TITLE
Rendering training data

### ISSUE THREAD

**Issue by AndreeaDogaru** [DaLi-Jack/SSR-code#8]
Hi. Thank you for your great work and for making the preprocessed data available!
Is it possible for you to also share the code used for rendering the depth map and other attributes?
I'm currently using BlenderProc to this end, and noticed that the scenes loaded with the Front3D dataloader do not perfectly match the provided RGB images (depth, etc.). For example, in the test split the lamp in the image 000746_rgb_003821 is rotated 
Original rendered image             |  BlenderProc rendered scene
:-------------------------:|:-------------------------:
![000746_rgb_003821](https://github.com/DaLi-Jack/SSR-code/assets/43440153/55fee58a-72f0-456f-9c95-fd2c41d777a7)  |  ![rendered](https://github.com/DaLi-Jack/SSR-code/assets/43440153/d4c7031f-b7c6-4e82-ab91-bff6405d2979)

**Comment by DaLi-Jack** [comment]
Hello! Thank you for your interest in our work!
We also use Blenderproc to generate data.
I noticed that your question can be divided into two parts, “_Why are the colors different?_” and "_Why are some objects rotating?_".
**1. Why are the colors different?**
This is because the RGB image I provided is not directly rendered by us, but provided by the official rendering of the Alibaba team. The open-source 3D Front dataset does not include the textures of objects and ambient light when the Alibaba team rendered these images at the time, so the RGB images rendered using Blenderproc will be different from the original images. The RGB image we rendered is similar to the color of your object. I think your color is reasonable.
**2. Why are some objects rotating?**
I think you may have encountered a problem we had with rendering at the time, **the Front3DLoader provided by Blenderproc had a rotation bug( in Front3DLoader.py)**, so I changed the source code of Blenderproc and got the correct results as follows. 
(I show the depth map)
![image](https://github.com/DaLi-Jack/SSR-code/assets/70205757/14ea8f13-f891-4691-ab0d-bd2fbccf0c9a)
Below is my changed `Front3DLoader.py` code, you can replace the original code and try again.
[Front3DLoader.py](https://drive.google.com/file/d/1-DluUhT8_NPzm6xgLCgT7npIQcUJ4Wgy/view?usp=drive_link)
The location and replacement method of the source code are as follows:
![image](https://github.com/DaLi-Jack/SSR-code/assets/70205757/4e387ebc-234b-4ac8-aae8-65fc7374468b)
In the picture above, `Front3DLoader-old.py` is the source code, and `Front3DLoader.py` is the code after I changed it. You can do this similarly. I ensured that the interface function remains unchanged when making changes, so just replace the file directly.
I hope my answer can solve your problem! 
And if it is useful to others, I will open source my data processing code after the Spring Festival.
Happy Spring Festival!

**Comment by AndreeaDogaru** [comment]
Thanks a lot, this is very helpful. 
Happy Spring Festival!

**Comment by ThePassedWind** [comment]
> Hello! Thank you for your interest in our work! We also use Blenderproc to generate data. I noticed that your question can be divided into two parts, “_Why are the colors different?_” and "_Why are some objects rotating?_". **1. Why are the colors different?** This is because the RGB image I provided is not directly rendered by us, but provided by the official rendering of the Alibaba team. The open-source 3D Front dataset does not include the textures of objects and ambient light when the Alibaba team rendered these images at the time, so the RGB images rendered using Blenderproc will be different from the original images. The RGB image we rendered is similar to the color of your object. I think your color is reasonable. **2. Why are some objects rotating?** I think you may have encountered a problem we had with rendering at the time, **the Front3DLoader provided by Blenderproc had a rotation bug( in Front3DLoader.py)**, so I changed the source code of Blenderproc and got the correct results as follows. (I show the depth map) ![image](https://private-user-images.githubusercontent.com/70205757/303324349-14ea8f13-f891-4691-ab0d-bd2fbccf0c9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODAxMzYsIm5iZiI6MTcyNDM3OTgzNiwicGF0aCI6Ii83MDIwNTc1Ny8zMDMzMjQzNDktMTRlYThmMTMtZjg5MS00NjkxLWFiMGQtYmQyZmJjY2YwYzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAyMjM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZmVjNTUwNzE3ZjVmMjkxMzJlMzIzZTU5MjJkZDUxNzg0MGEwZDQxODYwYWQ2MTkwNmE0ZDJmNGEzZGFlMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZSJnx0_kh0XkMxK_hKZp8lW4sSfx4-eHZdtG3SySTQ) Below is my changed `Front3DLoader.py` code, you can replace the original code and try again. [Front3DLoader.py](https://drive.google.com/file/d/1-DluUhT8_NPzm6xgLCgT7npIQcUJ4Wgy/view?usp=drive_link) The location and replacement method of the source code are as follows: ![image](https://private-user-images.githubusercontent.com/70205757/303325883-4e387ebc-234b-4ac8-aae8-65fc7374468b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODAxMzYsIm5iZiI6MTcyNDM3OTgzNiwicGF0aCI6Ii83MDIwNTc1Ny8zMDMzMjU4ODMtNGUzODdlYmMtMjM0Yi00YWM4LWFhZTgtNjVmYzczNzQ0NjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAyMjM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliN2U1MGI4YTZhN2M4ZTgyZmUyYmM4ZTJmY2IzNWIwOWY3M2Q2MDZkMDg1Y2FjMGIyMzM0YzZjYTU4MmQ3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oVaTjhjuUKW0eiqm9XASdfOONI8Yq-e6-TSPfpg07Lo) In the picture above, `Front3DLoader-old.py` is the source code, and `Front3DLoader.py` is the code after I changed it. You can do this similarly. I ensured that the interface function remains unchanged when making changes, so just replace the file directly. I hope my answer can solve your problem! And if it is useful to others, I will open source my data processing code after the Spring Festival. Happy Spring Festival!

Hi, could you share the data processing code?
For rendering the same poses and same resolution as the given RGB image, I want to ask how to set poses and intrinsics.
For example, using the code as below: 
https://github.com/DLR-RM/BlenderProc/blob/main/examples/datasets/front_3d/main.py
